"""Step 1 compose: NO LLM yet. Just group items by source/group, sort by date,
and emit a markdown preview so we can sanity-check the data flow.

Step 3 will replace this with: filter (LLM-cheap) -> cluster -> synth (LLM-strong).
"""

from __future__ import annotations

from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Iterable

from .items import Item
from .sources import Group, Source
from .storage import REPORTS_DIR, week_bounds


TIER_ORDER = {"S": 0, "A": 1, "B": 2}
TIER_BADGE = {"S": "🅢", "A": "🅐", "B": "🅑"}


def _parse_iso(s: str) -> datetime | None:
    if not s:
        return None
    try:
        return datetime.fromisoformat(s.replace("Z", "+00:00"))
    except Exception:
        return None


def filter_in_week(items: Iterable[dict], week_id: str) -> list[dict]:
    start, end = week_bounds(week_id)
    out: list[dict] = []
    for it in items:
        dt = _parse_iso(it.get("published_at", ""))
        if dt is None:
            continue
        if start <= dt < end:
            out.append(it)
    return out


def compose_preview_md(
    week_id: str,
    items: list[dict],
    sources: list[Source],
    groups: list[Group],
) -> str:
    src_by_id = {s.id: s for s in sources}
    group_by_id = {g.id: g for g in groups}

    # group items: group_id -> source_id -> [items]
    bucket: dict[str, dict[str, list[dict]]] = defaultdict(lambda: defaultdict(list))
    for it in items:
        sid = it["source_id"]
        s = src_by_id.get(sid)
        if not s:
            continue
        bucket[s.group_id][sid].append(it)

    # sort items by published_at desc within each source
    for gid in bucket:
        for sid in bucket[gid]:
            bucket[gid][sid].sort(key=lambda x: x.get("published_at", ""), reverse=True)

    start, end = week_bounds(week_id)

    lines: list[str] = []
    lines.append(f"# Weekly Preview · {week_id}")
    lines.append("")
    lines.append(
        f"_Window:_ `{start.date()} → {(end.date())}` (UTC, exclusive end) · "
        f"_Items:_ **{len(items)}** · _Sources active:_ "
        f"**{sum(1 for g in bucket.values() for _ in g)}**"
    )
    lines.append("")
    lines.append(
        "> ⚠️ **Step 1 preview** — no LLM filter / synthesis yet. "
        "This is just raw items from this week, grouped by source, "
        "to verify the ingest pipeline."
    )
    lines.append("")

    # tally by source for the top
    tally = sorted(
        ((sid, len(items)) for gid in bucket for sid, items in bucket[gid].items()),
        key=lambda x: -x[1],
    )
    lines.append("## Source tally (this week)")
    lines.append("")
    lines.append("| # | Source | Tier | Items |")
    lines.append("| --- | --- | --- | --- |")
    for sid, n in tally:
        s = src_by_id[sid]
        lines.append(f"| {TIER_BADGE.get(s.tier, '·')} | {s.name} | {s.tier} | {n} |")
    lines.append("")

    # body, by group then by source
    sorted_gids = sorted(
        bucket.keys(),
        key=lambda gid: (group_by_id.get(gid, Group(gid, gid)).name),
    )
    for gid in sorted_gids:
        g = group_by_id.get(gid, Group(gid, gid))
        lines.append(f"## {g.name}")
        if g.subtitle:
            lines.append(f"_{g.subtitle}_")
        lines.append("")

        sorted_sids = sorted(
            bucket[gid].keys(),
            key=lambda sid: (
                TIER_ORDER.get(src_by_id[sid].tier, 9),
                src_by_id[sid].name,
            ),
        )
        for sid in sorted_sids:
            s = src_by_id[sid]
            its = bucket[gid][sid]
            lines.append(
                f"### {TIER_BADGE.get(s.tier, '·')} {s.name}  "
                f"<sup>{s.tier} · {s.type} · {len(its)} items</sup>"
            )
            for it in its:
                dt = _parse_iso(it.get("published_at", ""))
                date_str = dt.strftime("%m-%d") if dt else "?"
                title = it.get("title", "(untitled)").strip()
                url = it.get("url", "")
                lines.append(f"- `{date_str}` [{title}]({url})")
                summary = (it.get("summary") or "").strip()
                if summary:
                    short = summary[:240].rstrip()
                    if len(summary) > 240:
                        short += "…"
                    lines.append(f"  - {short}")
            lines.append("")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(
        "_Generated by `weekly_report` (Step 1: ingest preview, no LLM)._"
    )
    return "\n".join(lines)


def write_preview(week_id: str, md: str) -> Path:
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    path = REPORTS_DIR / f"{week_id}-preview.md"
    path.write_text(md, encoding="utf-8")
    return path
